# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/MovingSquare_VGA_Controller_0_0.xci
# IP: The module: 'MovingSquare_VGA_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/VGA_Controller_Adders_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_Adders_0_0 || ORIG_REF_NAME==VGA_Controller_Adders_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_c_addsub_0_0/Adders_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_c_addsub_0_0 || ORIG_REF_NAME==Adders_c_addsub_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFP_0/Adders_SWplusHorFP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFP_0 || ORIG_REF_NAME==Adders_SWplusHorFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFPplusHSync_0/Adders_SWplusHorFPplusHSync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFPplusHSync_0 || ORIG_REF_NAME==Adders_SWplusHorFPplusHSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalHor_0/Adders_TotalHor_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_0 || ORIG_REF_NAME==Adders_TotalHor_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_xlconstant_0_0/Adders_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_xlconstant_0_0 || ORIG_REF_NAME==Adders_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalHor_2/Adders_TotalHor_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_2 || ORIG_REF_NAME==Adders_TotalHor_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFP_0/Adders_SHplusVerFP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFP_0 || ORIG_REF_NAME==Adders_SHplusVerFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFPplusVSync_0/Adders_SHplusVerFPplusVSync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFPplusVSync_0 || ORIG_REF_NAME==Adders_SHplusVerFPplusVSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalVer_0/Adders_TotalVer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalVer_0 || ORIG_REF_NAME==Adders_TotalVer_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_clk_wiz_0_0 || ORIG_REF_NAME==VGA_Controller_clk_wiz_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_c_counter_binary_0_0/VGA_Controller_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_c_counter_binary_0_0 || ORIG_REF_NAME==VGA_Controller_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/VGA_Controller_H_comps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_H_comps_0_0 || ORIG_REF_NAME==VGA_Controller_H_comps_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_DS_COMP_16B_0_0/H_comps_DS_COMP_16B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_DS_COMP_16B_0_0 || ORIG_REF_NAME==H_comps_DS_COMP_16B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_WidthEQ_0/H_comps_WidthEQ_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_WidthEQ_0 || ORIG_REF_NAME==H_comps_WidthEQ_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_Width_FPEQ1_0/H_comps_Width_FPEQ1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_Width_FPEQ1_0 || ORIG_REF_NAME==H_comps_Width_FPEQ1_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_Width_FP_SyncEQ2_0/H_comps_Width_FP_SyncEQ2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_Width_FP_SyncEQ2_0 || ORIG_REF_NAME==H_comps_Width_FP_SyncEQ2_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_DS_OR_2B_0_0/VGA_Controller_DS_OR_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_DS_OR_2B_0_0 || ORIG_REF_NAME==VGA_Controller_DS_OR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_c_counter_binary_0_1/VGA_Controller_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_c_counter_binary_0_1 || ORIG_REF_NAME==VGA_Controller_c_counter_binary_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/VGA_Controller_V_comps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_V_comps_0_0 || ORIG_REF_NAME==VGA_Controller_V_comps_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_DS_COMP_16B_0_0/V_comps_DS_COMP_16B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_DS_COMP_16B_0_0 || ORIG_REF_NAME==V_comps_DS_COMP_16B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_HightEQ_0/V_comps_HightEQ_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_HightEQ_0 || ORIG_REF_NAME==V_comps_HightEQ_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_Hight_FPEQ1_0/V_comps_Hight_FPEQ1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_Hight_FPEQ1_0 || ORIG_REF_NAME==V_comps_Hight_FPEQ1_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_Hight_FP_SyncEQ_0/V_comps_Hight_FP_SyncEQ_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_Hight_FP_SyncEQ_0 || ORIG_REF_NAME==V_comps_Hight_FP_SyncEQ_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/VGA_Controller_VGA_Logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_VGA_Logic_0_0 || ORIG_REF_NAME==VGA_Controller_VGA_Logic_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_0/VGA_Logic_DS_EXOR_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_1/VGA_Logic_DS_NOT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_1 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_1/VGA_Logic_DS_EXOR_2B_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_1 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_2/VGA_Logic_DS_NOT_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_2 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_0_0/VGA_Logic_DS_AND_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_1_0/VGA_Logic_DS_AND_2B_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_1_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_1_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_DS_AND_2B_0_0/VGA_Controller_DS_AND_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Controller_DS_AND_2B_0_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_Controller_clk_wiz_0_0 || ORIG_REF_NAME==VGA_Controller_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_VGA_Controller_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/MovingSquare_VGA_Controller_0_0.xci
# IP: The module: 'MovingSquare_VGA_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/VGA_Controller_Adders_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_Adders_0_0 || ORIG_REF_NAME==VGA_Controller_Adders_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_c_addsub_0_0/Adders_c_addsub_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_c_addsub_0_0 || ORIG_REF_NAME==Adders_c_addsub_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFP_0/Adders_SWplusHorFP_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFP_0 || ORIG_REF_NAME==Adders_SWplusHorFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFPplusHSync_0/Adders_SWplusHorFPplusHSync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFPplusHSync_0 || ORIG_REF_NAME==Adders_SWplusHorFPplusHSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalHor_0/Adders_TotalHor_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_0 || ORIG_REF_NAME==Adders_TotalHor_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_xlconstant_0_0/Adders_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_xlconstant_0_0 || ORIG_REF_NAME==Adders_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalHor_2/Adders_TotalHor_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_2 || ORIG_REF_NAME==Adders_TotalHor_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFP_0/Adders_SHplusVerFP_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFP_0 || ORIG_REF_NAME==Adders_SHplusVerFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFPplusVSync_0/Adders_SHplusVerFPplusVSync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFPplusVSync_0 || ORIG_REF_NAME==Adders_SHplusVerFPplusVSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalVer_0/Adders_TotalVer_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalVer_0 || ORIG_REF_NAME==Adders_TotalVer_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_clk_wiz_0_0 || ORIG_REF_NAME==VGA_Controller_clk_wiz_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_c_counter_binary_0_0/VGA_Controller_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_c_counter_binary_0_0 || ORIG_REF_NAME==VGA_Controller_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/VGA_Controller_H_comps_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_H_comps_0_0 || ORIG_REF_NAME==VGA_Controller_H_comps_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_DS_COMP_16B_0_0/H_comps_DS_COMP_16B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_DS_COMP_16B_0_0 || ORIG_REF_NAME==H_comps_DS_COMP_16B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_WidthEQ_0/H_comps_WidthEQ_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_WidthEQ_0 || ORIG_REF_NAME==H_comps_WidthEQ_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_Width_FPEQ1_0/H_comps_Width_FPEQ1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_Width_FPEQ1_0 || ORIG_REF_NAME==H_comps_Width_FPEQ1_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_Width_FP_SyncEQ2_0/H_comps_Width_FP_SyncEQ2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==H_comps_Width_FP_SyncEQ2_0 || ORIG_REF_NAME==H_comps_Width_FP_SyncEQ2_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_DS_OR_2B_0_0/VGA_Controller_DS_OR_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_DS_OR_2B_0_0 || ORIG_REF_NAME==VGA_Controller_DS_OR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_c_counter_binary_0_1/VGA_Controller_c_counter_binary_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_c_counter_binary_0_1 || ORIG_REF_NAME==VGA_Controller_c_counter_binary_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/VGA_Controller_V_comps_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_V_comps_0_0 || ORIG_REF_NAME==VGA_Controller_V_comps_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_DS_COMP_16B_0_0/V_comps_DS_COMP_16B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_DS_COMP_16B_0_0 || ORIG_REF_NAME==V_comps_DS_COMP_16B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_HightEQ_0/V_comps_HightEQ_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_HightEQ_0 || ORIG_REF_NAME==V_comps_HightEQ_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_Hight_FPEQ1_0/V_comps_Hight_FPEQ1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_Hight_FPEQ1_0 || ORIG_REF_NAME==V_comps_Hight_FPEQ1_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_Hight_FP_SyncEQ_0/V_comps_Hight_FP_SyncEQ_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==V_comps_Hight_FP_SyncEQ_0 || ORIG_REF_NAME==V_comps_Hight_FP_SyncEQ_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/VGA_Controller_VGA_Logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_VGA_Logic_0_0 || ORIG_REF_NAME==VGA_Controller_VGA_Logic_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_0/VGA_Logic_DS_EXOR_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_1/VGA_Logic_DS_NOT_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_1 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_1/VGA_Logic_DS_EXOR_2B_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_1 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_2/VGA_Logic_DS_NOT_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_2 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_0_0/VGA_Logic_DS_AND_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_1_0/VGA_Logic_DS_AND_2B_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_1_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_1_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_DS_AND_2B_0_0/VGA_Controller_DS_AND_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Controller_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Controller_DS_AND_2B_0_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_Controller_clk_wiz_0_0 || ORIG_REF_NAME==VGA_Controller_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_ooc.xdc

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_VGA_Controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
