@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Apr 19 12:16:55 +0200 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim VGA_Controller_TB_behav -key {Behavioral:sim_1:Functional:VGA_Controller_TB} -tclbatch VGA_Controller_TB.tcl -protoinst "protoinst_files/Adders.protoinst" -protoinst "protoinst_files/H_comps.protoinst" -protoinst "protoinst_files/V_comps.protoinst" -protoinst "protoinst_files/VGA_Logic.protoinst" -protoinst "protoinst_files/VGA_Controller.protoinst" -log simulate.log"
call xsim  VGA_Controller_TB_behav -key {Behavioral:sim_1:Functional:VGA_Controller_TB} -tclbatch VGA_Controller_TB.tcl -protoinst "protoinst_files/Adders.protoinst" -protoinst "protoinst_files/H_comps.protoinst" -protoinst "protoinst_files/V_comps.protoinst" -protoinst "protoinst_files/VGA_Logic.protoinst" -protoinst "protoinst_files/VGA_Controller.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
