# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/MovingSquare_Comps_0_0.xci
# IP: The module: 'MovingSquare_Comps_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_DS_COMP_16B_0_0/Comps_DS_COMP_16B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_DS_COMP_16B_0_0 || ORIG_REF_NAME==Comps_DS_COMP_16B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_GT_endX_0/Comps_X_GT_endX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_GT_endX_0 || ORIG_REF_NAME==Comps_X_GT_endX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_LT_startX_0/Comps_X_LT_startX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_LT_startX_0 || ORIG_REF_NAME==Comps_X_LT_startX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_Y_LT_startY_0/Comps_Y_LT_startY_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_Y_LT_startY_0 || ORIG_REF_NAME==Comps_Y_LT_startY_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_LT_startX_1/Comps_X_LT_startX_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_LT_startX_1 || ORIG_REF_NAME==Comps_X_LT_startX_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_Y_GT_endY_0/Comps_Y_GT_endY_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_Y_GT_endY_0 || ORIG_REF_NAME==Comps_Y_GT_endY_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_GT_endX_1/Comps_X_GT_endX_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_GT_endX_1 || ORIG_REF_NAME==Comps_X_GT_endX_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_xlconstant_0_0/Comps_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_xlconstant_0_0 || ORIG_REF_NAME==Comps_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_EQ_0_0/Comps_X_EQ_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_EQ_0_0 || ORIG_REF_NAME==Comps_X_EQ_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_EQ_0_1/Comps_X_EQ_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_EQ_0_1 || ORIG_REF_NAME==Comps_X_EQ_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_endY_EQ_SH_0/Comps_endY_EQ_SH_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_endY_EQ_SH_0 || ORIG_REF_NAME==Comps_endY_EQ_SH_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_Comps_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/MovingSquare_Comps_0_0.xci
# IP: The module: 'MovingSquare_Comps_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_DS_COMP_16B_0_0/Comps_DS_COMP_16B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_DS_COMP_16B_0_0 || ORIG_REF_NAME==Comps_DS_COMP_16B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_GT_endX_0/Comps_X_GT_endX_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_GT_endX_0 || ORIG_REF_NAME==Comps_X_GT_endX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_LT_startX_0/Comps_X_LT_startX_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_LT_startX_0 || ORIG_REF_NAME==Comps_X_LT_startX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_Y_LT_startY_0/Comps_Y_LT_startY_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_Y_LT_startY_0 || ORIG_REF_NAME==Comps_Y_LT_startY_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_LT_startX_1/Comps_X_LT_startX_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_LT_startX_1 || ORIG_REF_NAME==Comps_X_LT_startX_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_Y_GT_endY_0/Comps_Y_GT_endY_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_Y_GT_endY_0 || ORIG_REF_NAME==Comps_Y_GT_endY_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_GT_endX_1/Comps_X_GT_endX_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_GT_endX_1 || ORIG_REF_NAME==Comps_X_GT_endX_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_xlconstant_0_0/Comps_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_xlconstant_0_0 || ORIG_REF_NAME==Comps_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_EQ_0_0/Comps_X_EQ_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_EQ_0_0 || ORIG_REF_NAME==Comps_X_EQ_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_EQ_0_1/Comps_X_EQ_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_X_EQ_0_1 || ORIG_REF_NAME==Comps_X_EQ_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_endY_EQ_SH_0/Comps_endY_EQ_SH_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Comps_endY_EQ_SH_0 || ORIG_REF_NAME==Comps_endY_EQ_SH_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_Comps_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
