# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/VGA_Controller_Adders_0_0.xci
# IP: The module: 'VGA_Controller_Adders_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_c_addsub_0_0/Adders_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_c_addsub_0_0 || ORIG_REF_NAME==Adders_c_addsub_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFP_0/Adders_SWplusHorFP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFP_0 || ORIG_REF_NAME==Adders_SWplusHorFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFPplusHSync_0/Adders_SWplusHorFPplusHSync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFPplusHSync_0 || ORIG_REF_NAME==Adders_SWplusHorFPplusHSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_TotalHor_0/Adders_TotalHor_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_0 || ORIG_REF_NAME==Adders_TotalHor_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_xlconstant_0_0/Adders_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_xlconstant_0_0 || ORIG_REF_NAME==Adders_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_TotalHor_2/Adders_TotalHor_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_2 || ORIG_REF_NAME==Adders_TotalHor_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFP_0/Adders_SHplusVerFP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFP_0 || ORIG_REF_NAME==Adders_SHplusVerFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFPplusVSync_0/Adders_SHplusVerFPplusVSync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFPplusVSync_0 || ORIG_REF_NAME==Adders_SHplusVerFPplusVSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_TotalVer_0/Adders_TotalVer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalVer_0 || ORIG_REF_NAME==Adders_TotalVer_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_Controller_Adders_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/VGA_Controller_Adders_0_0.xci
# IP: The module: 'VGA_Controller_Adders_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_c_addsub_0_0/Adders_c_addsub_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_c_addsub_0_0 || ORIG_REF_NAME==Adders_c_addsub_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFP_0/Adders_SWplusHorFP_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFP_0 || ORIG_REF_NAME==Adders_SWplusHorFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFPplusHSync_0/Adders_SWplusHorFPplusHSync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SWplusHorFPplusHSync_0 || ORIG_REF_NAME==Adders_SWplusHorFPplusHSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_TotalHor_0/Adders_TotalHor_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_0 || ORIG_REF_NAME==Adders_TotalHor_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_xlconstant_0_0/Adders_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_xlconstant_0_0 || ORIG_REF_NAME==Adders_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_TotalHor_2/Adders_TotalHor_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalHor_2 || ORIG_REF_NAME==Adders_TotalHor_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFP_0/Adders_SHplusVerFP_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFP_0 || ORIG_REF_NAME==Adders_SHplusVerFP_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFPplusVSync_0/Adders_SHplusVerFPplusVSync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_SHplusVerFPplusVSync_0 || ORIG_REF_NAME==Adders_SHplusVerFPplusVSync_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_TotalVer_0/Adders_TotalVer_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adders_TotalVer_0 || ORIG_REF_NAME==Adders_TotalVer_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_Adders_0_0/src/Adders_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_Controller_Adders_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
