# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/MovingSquare_SquareOrScreen_0_0.xci
# IP: The module: 'MovingSquare_SquareOrScreen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_AND_2B_0_0/SquareOrScreen_DS_AND_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_DS_AND_2B_0_0 || ORIG_REF_NAME==SquareOrScreen_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_0/SquareOrScreen_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconcat_0_0 || ORIG_REF_NAME==SquareOrScreen_xlconcat_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_1/SquareOrScreen_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconcat_0_1 || ORIG_REF_NAME==SquareOrScreen_xlconcat_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_2/SquareOrScreen_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconcat_0_2 || ORIG_REF_NAME==SquareOrScreen_xlconcat_0_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconstant_0_0/SquareOrScreen_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconstant_0_0 || ORIG_REF_NAME==SquareOrScreen_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_AND_2B_0_1/SquareOrScreen_DS_AND_2B_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_DS_AND_2B_0_1 || ORIG_REF_NAME==SquareOrScreen_DS_AND_2B_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_NOT_0_0/SquareOrScreen_DS_NOT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_DS_NOT_0_0 || ORIG_REF_NAME==SquareOrScreen_DS_NOT_0_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_SquareOrScreen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/MovingSquare_SquareOrScreen_0_0.xci
# IP: The module: 'MovingSquare_SquareOrScreen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_AND_2B_0_0/SquareOrScreen_DS_AND_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_DS_AND_2B_0_0 || ORIG_REF_NAME==SquareOrScreen_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_0/SquareOrScreen_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconcat_0_0 || ORIG_REF_NAME==SquareOrScreen_xlconcat_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_1/SquareOrScreen_xlconcat_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconcat_0_1 || ORIG_REF_NAME==SquareOrScreen_xlconcat_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_2/SquareOrScreen_xlconcat_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconcat_0_2 || ORIG_REF_NAME==SquareOrScreen_xlconcat_0_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconstant_0_0/SquareOrScreen_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_xlconstant_0_0 || ORIG_REF_NAME==SquareOrScreen_xlconstant_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_AND_2B_0_1/SquareOrScreen_DS_AND_2B_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_DS_AND_2B_0_1 || ORIG_REF_NAME==SquareOrScreen_DS_AND_2B_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_NOT_0_0/SquareOrScreen_DS_NOT_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SquareOrScreen_DS_NOT_0_0 || ORIG_REF_NAME==SquareOrScreen_DS_NOT_0_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_SquareOrScreen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
