#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : MovingSquare.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Apr 24 16:12:03 +0200 2020
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: MovingSquare.sh [-help]
# usage: MovingSquare.sh [-lib_map_path]
# usage: MovingSquare.sh [-noclean_files]
# usage: MovingSquare.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'MovingSquare.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 xil_defaultlib xlconstant_v1_1_6 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 xlconcat_v2_1_3)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "MovingSquare.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "D:/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/b795/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_c_addsub_0_0/sim/Adders_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFP_0/sim/Adders_SWplusHorFP_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SWplusHorFPplusHSync_0/sim/Adders_SWplusHorFPplusHSync_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalHor_0/sim/Adders_TotalHor_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_xlconstant_0_0/sim/Adders_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalHor_2/sim/Adders_TotalHor_2.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFP_0/sim/Adders_SHplusVerFP_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_SHplusVerFPplusVSync_0/sim/Adders_SHplusVerFPplusVSync_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/src/Adders_TotalVer_0/sim/Adders_TotalVer_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/0a4e/sim/Adders.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_Adders_0_0/sim/VGA_Controller_Adders_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_clk_wiz_0_0/VGA_Controller_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/1f12/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_c_counter_binary_0_0/sim/VGA_Controller_c_counter_binary_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/ipshared/3bbb/COMP.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_DS_COMP_16B_0_0/sim/H_comps_DS_COMP_16B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_WidthEQ_0/sim/H_comps_WidthEQ_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_Width_FPEQ1_0/sim/H_comps_Width_FPEQ1_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/src/H_comps_Width_FP_SyncEQ2_0/sim/H_comps_Width_FP_SyncEQ2_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/b238/sim/H_comps.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_H_comps_0_0/sim/VGA_Controller_H_comps_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/e6ac/sources_1/new/DS_OR_2B.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_DS_OR_2B_0_0/sim/VGA_Controller_DS_OR_2B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_c_counter_binary_0_1/sim/VGA_Controller_c_counter_binary_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_DS_COMP_16B_0_0/sim/V_comps_DS_COMP_16B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_HightEQ_0/sim/V_comps_HightEQ_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_Hight_FPEQ1_0/sim/V_comps_Hight_FPEQ1_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/src/V_comps_Hight_FP_SyncEQ_0/sim/V_comps_Hight_FP_SyncEQ_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/c2ef/sim/V_comps.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_V_comps_0_0/sim/VGA_Controller_V_comps_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/ipshared/8252/sources_1/new/DS_EXOR_2B.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_0/sim/VGA_Logic_DS_EXOR_2B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/ipshared/41fb/sources_1/new/DS_NOT.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_1/sim/VGA_Logic_DS_NOT_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_1/sim/VGA_Logic_DS_EXOR_2B_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_2/sim/VGA_Logic_DS_NOT_0_2.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/ipshared/49a8/sources_1/new/DS_AND_2B.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_0_0/sim/VGA_Logic_DS_AND_2B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_1_0/sim/VGA_Logic_DS_AND_2B_1_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/cf48/sim/VGA_Logic.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_VGA_Logic_0_0/sim/VGA_Controller_VGA_Logic_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/src/VGA_Controller_DS_AND_2B_0_0/sim/VGA_Controller_DS_AND_2B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ipshared/915d/sim/VGA_Controller.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/sim/MovingSquare_VGA_Controller_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_c_counter_binary_0_0/sim/X_Y_Values_c_counter_binary_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_c_addsub_0_0/sim/X_Y_Values_c_addsub_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_EndX_0/sim/X_Y_Values_EndX_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_MovingX_0/sim/X_Y_Values_MovingX_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_EndX_1/sim/X_Y_Values_EndX_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_CE_0/sim/X_Y_Values_CE_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_Delay1Pulse_0/sim/X_Y_Values_Delay1Pulse_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_xlconstant_0_0/sim/X_Y_Values_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ipshared/eaa3/sim/X_Y_Values.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/sim/MovingSquare_X_Y_Values_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_xlconstant_0_0/sim/MovingSquare_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SQ_HeightPlus1_0/sim/MovingSquare_SQ_HeightPlus1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_DS_COMP_16B_0_0/sim/Comps_DS_COMP_16B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_GT_endX_0/sim/Comps_X_GT_endX_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_LT_startX_0/sim/Comps_X_LT_startX_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_Y_LT_startY_0/sim/Comps_Y_LT_startY_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_LT_startX_1/sim/Comps_X_LT_startX_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_Y_GT_endY_0/sim/Comps_Y_GT_endY_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_GT_endX_1/sim/Comps_X_GT_endX_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_xlconstant_0_0/sim/Comps_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_EQ_0_0/sim/Comps_X_EQ_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_X_EQ_0_1/sim/Comps_X_EQ_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/src/Comps_endY_EQ_SH_0/sim/Comps_endY_EQ_SH_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ipshared/508e/sim/Comps.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_Comps_0_0/sim/MovingSquare_Comps_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_xlconstant_0_1/sim/MovingSquare_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HSync_in_0/sim/MovingSquare_HSync_in_0.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HSync_in_1/sim/MovingSquare_HSync_in_1.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HorBP_0/sim/MovingSquare_HorBP_0.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HorBP_1/sim/MovingSquare_HorBP_1.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HorBP_2/sim/MovingSquare_HorBP_2.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HorBP_3/sim/MovingSquare_HorBP_3.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_HorBP_4/sim/MovingSquare_HorBP_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_AND_2B_0_0/sim/VGA_Square_Logic_DS_AND_2B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_NOT_0_0/sim/VGA_Square_Logic_DS_NOT_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_X_NOT_GT_endX_0/sim/VGA_Square_Logic_X_NOT_GT_endX_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InWidthSquare_0/sim/VGA_Square_Logic_InWidthSquare_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InWidthSquare_1/sim/VGA_Square_Logic_InWidthSquare_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_X_NOT_LT_startX_0/sim/VGA_Square_Logic_X_NOT_LT_startX_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_Y_NOT_LT_startY_0/sim/VGA_Square_Logic_Y_NOT_LT_startY_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InSquare_0/sim/VGA_Square_Logic_InSquare_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InSquareAndCanDraw_0/sim/VGA_Square_Logic_InSquareAndCanDraw_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_YANDX_0_0/sim/VGA_Square_Logic_YANDX_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_OR_2B_0_0/sim/VGA_Square_Logic_DS_OR_2B_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_SideReached_0/sim/VGA_Square_Logic_SideReached_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_c_counter_binary_0_1/sim/VGA_Square_Logic_c_counter_binary_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_Toggle_X_Up_0/sim/VGA_Square_Logic_Toggle_X_Up_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_NOT_0_1/sim/VGA_Square_Logic_DS_NOT_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_startWithX_Up_High_0/sim/VGA_Square_Logic_startWithX_Up_High_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ipshared/2724/sim/VGA_Square_Logic.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/sim/MovingSquare_VGA_Square_Logic_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_AND_2B_0_0/sim/SquareOrScreen_DS_AND_2B_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/ipshared/4fba" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_0/sim/SquareOrScreen_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_1/sim/SquareOrScreen_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconcat_0_2/sim/SquareOrScreen_xlconcat_0_2.v" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_xlconstant_0_0/sim/SquareOrScreen_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_AND_2B_0_1/sim/SquareOrScreen_DS_AND_2B_0_1.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/src/SquareOrScreen_DS_NOT_0_0/sim/SquareOrScreen_DS_NOT_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ipshared/c072/sim/SquareOrScreen.vhd" \
    "$ref_dir/../../../bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/sim/MovingSquare_SquareOrScreen_0_0.vhd" \
    "$ref_dir/../../../bd/MovingSquare/sim/MovingSquare.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.MovingSquare xil_defaultlib.glbl -o MovingSquare_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./MovingSquare_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./MovingSquare.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key MovingSquare_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc MovingSquare_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./MovingSquare.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: MovingSquare.sh [-help]\n\
Usage: MovingSquare.sh [-lib_map_path]\n\
Usage: MovingSquare.sh [-reset_run]\n\
Usage: MovingSquare.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
