# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CONSTRAINT.xdc

# Block Designs: bd/MovingSquare/MovingSquare.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare || ORIG_REF_NAME==MovingSquare} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_VGA_Controller_0_0/MovingSquare_VGA_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_VGA_Controller_0_0 || ORIG_REF_NAME==MovingSquare_VGA_Controller_0_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/MovingSquare_X_Y_Values_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_X_Y_Values_0_0 || ORIG_REF_NAME==MovingSquare_X_Y_Values_0_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_xlconstant_0_0/MovingSquare_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_xlconstant_0_0 || ORIG_REF_NAME==MovingSquare_xlconstant_0_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_SQ_HeightPlus1_0/MovingSquare_SQ_HeightPlus1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_SQ_HeightPlus1_0 || ORIG_REF_NAME==MovingSquare_SQ_HeightPlus1_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_Comps_0_0/MovingSquare_Comps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_Comps_0_0 || ORIG_REF_NAME==MovingSquare_Comps_0_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_xlconstant_0_1/MovingSquare_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_xlconstant_0_1 || ORIG_REF_NAME==MovingSquare_xlconstant_0_1} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HSync_in_0/MovingSquare_HSync_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HSync_in_0 || ORIG_REF_NAME==MovingSquare_HSync_in_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HSync_in_1/MovingSquare_HSync_in_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HSync_in_1 || ORIG_REF_NAME==MovingSquare_HSync_in_1} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HorBP_0/MovingSquare_HorBP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HorBP_0 || ORIG_REF_NAME==MovingSquare_HorBP_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HorBP_1/MovingSquare_HorBP_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HorBP_1 || ORIG_REF_NAME==MovingSquare_HorBP_1} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HorBP_2/MovingSquare_HorBP_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HorBP_2 || ORIG_REF_NAME==MovingSquare_HorBP_2} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HorBP_3/MovingSquare_HorBP_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HorBP_3 || ORIG_REF_NAME==MovingSquare_HorBP_3} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_HorBP_4/MovingSquare_HorBP_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_HorBP_4 || ORIG_REF_NAME==MovingSquare_HorBP_4} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/MovingSquare_VGA_Square_Logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_VGA_Square_Logic_0_0 || ORIG_REF_NAME==MovingSquare_VGA_Square_Logic_0_0} -quiet] -quiet

# IP: bd/MovingSquare/ip/MovingSquare_SquareOrScreen_0_0/MovingSquare_SquareOrScreen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MovingSquare_SquareOrScreen_0_0 || ORIG_REF_NAME==MovingSquare_SquareOrScreen_0_0} -quiet] -quiet

# XDC: bd/MovingSquare/MovingSquare_ooc.xdc
