# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/MovingSquare_X_Y_Values_0_0.xci
# IP: The module: 'MovingSquare_X_Y_Values_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_c_counter_binary_0_0/X_Y_Values_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_c_counter_binary_0_0 || ORIG_REF_NAME==X_Y_Values_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_c_addsub_0_0/X_Y_Values_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_c_addsub_0_0 || ORIG_REF_NAME==X_Y_Values_c_addsub_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_EndX_0/X_Y_Values_EndX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_EndX_0 || ORIG_REF_NAME==X_Y_Values_EndX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_MovingX_0/X_Y_Values_MovingX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_MovingX_0 || ORIG_REF_NAME==X_Y_Values_MovingX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_EndX_1/X_Y_Values_EndX_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_EndX_1 || ORIG_REF_NAME==X_Y_Values_EndX_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_CE_0/X_Y_Values_CE_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_CE_0 || ORIG_REF_NAME==X_Y_Values_CE_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_Delay1Pulse_0/X_Y_Values_Delay1Pulse_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_Delay1Pulse_0 || ORIG_REF_NAME==X_Y_Values_Delay1Pulse_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_xlconstant_0_0/X_Y_Values_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_xlconstant_0_0 || ORIG_REF_NAME==X_Y_Values_xlconstant_0_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_X_Y_Values_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/MovingSquare_X_Y_Values_0_0.xci
# IP: The module: 'MovingSquare_X_Y_Values_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_c_counter_binary_0_0/X_Y_Values_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_c_counter_binary_0_0 || ORIG_REF_NAME==X_Y_Values_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_c_addsub_0_0/X_Y_Values_c_addsub_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_c_addsub_0_0 || ORIG_REF_NAME==X_Y_Values_c_addsub_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_EndX_0/X_Y_Values_EndX_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_EndX_0 || ORIG_REF_NAME==X_Y_Values_EndX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_MovingX_0/X_Y_Values_MovingX_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_MovingX_0 || ORIG_REF_NAME==X_Y_Values_MovingX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_EndX_1/X_Y_Values_EndX_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_EndX_1 || ORIG_REF_NAME==X_Y_Values_EndX_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_CE_0/X_Y_Values_CE_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_CE_0 || ORIG_REF_NAME==X_Y_Values_CE_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_Delay1Pulse_0/X_Y_Values_Delay1Pulse_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_Delay1Pulse_0 || ORIG_REF_NAME==X_Y_Values_Delay1Pulse_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_xlconstant_0_0/X_Y_Values_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==X_Y_Values_xlconstant_0_0 || ORIG_REF_NAME==X_Y_Values_xlconstant_0_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_X_Y_Values_0_0/src/X_Y_Values_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_X_Y_Values_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
