# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/VGA_Controller_VGA_Logic_0_0.xci
# IP: The module: 'VGA_Controller_VGA_Logic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_0/VGA_Logic_DS_EXOR_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_1/VGA_Logic_DS_NOT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_1 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_1/VGA_Logic_DS_EXOR_2B_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_1 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_2/VGA_Logic_DS_NOT_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_2 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_0_0/VGA_Logic_DS_AND_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_1_0/VGA_Logic_DS_AND_2B_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_1_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_1_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_Controller_VGA_Logic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/VGA_Controller_VGA_Logic_0_0.xci
# IP: The module: 'VGA_Controller_VGA_Logic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_0/VGA_Logic_DS_EXOR_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_1/VGA_Logic_DS_NOT_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_1 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_EXOR_2B_0_1/VGA_Logic_DS_EXOR_2B_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_EXOR_2B_0_1 || ORIG_REF_NAME==VGA_Logic_DS_EXOR_2B_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_NOT_0_2/VGA_Logic_DS_NOT_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_NOT_0_2 || ORIG_REF_NAME==VGA_Logic_DS_NOT_0_2} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_0_0/VGA_Logic_DS_AND_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_DS_AND_2B_1_0/VGA_Logic_DS_AND_2B_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Logic_DS_AND_2B_1_0 || ORIG_REF_NAME==VGA_Logic_DS_AND_2B_1_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/VGA_Controller_v2/VGA_Controller_v2.srcs/sources_1/bd/VGA_Controller/ip/VGA_Controller_VGA_Logic_0_0/src/VGA_Logic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_Controller_VGA_Logic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
