# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/MovingSquare_VGA_Square_Logic_0_0.xci
# IP: The module: 'MovingSquare_VGA_Square_Logic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_AND_2B_0_0/VGA_Square_Logic_DS_AND_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Square_Logic_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_NOT_0_0/VGA_Square_Logic_DS_NOT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_NOT_0_0 || ORIG_REF_NAME==VGA_Square_Logic_DS_NOT_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_X_NOT_GT_endX_0/VGA_Square_Logic_X_NOT_GT_endX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_X_NOT_GT_endX_0 || ORIG_REF_NAME==VGA_Square_Logic_X_NOT_GT_endX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InWidthSquare_0/VGA_Square_Logic_InWidthSquare_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InWidthSquare_0 || ORIG_REF_NAME==VGA_Square_Logic_InWidthSquare_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InWidthSquare_1/VGA_Square_Logic_InWidthSquare_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InWidthSquare_1 || ORIG_REF_NAME==VGA_Square_Logic_InWidthSquare_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_X_NOT_LT_startX_0/VGA_Square_Logic_X_NOT_LT_startX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_X_NOT_LT_startX_0 || ORIG_REF_NAME==VGA_Square_Logic_X_NOT_LT_startX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_Y_NOT_LT_startY_0/VGA_Square_Logic_Y_NOT_LT_startY_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_Y_NOT_LT_startY_0 || ORIG_REF_NAME==VGA_Square_Logic_Y_NOT_LT_startY_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InSquare_0/VGA_Square_Logic_InSquare_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InSquare_0 || ORIG_REF_NAME==VGA_Square_Logic_InSquare_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InSquareAndCanDraw_0/VGA_Square_Logic_InSquareAndCanDraw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InSquareAndCanDraw_0 || ORIG_REF_NAME==VGA_Square_Logic_InSquareAndCanDraw_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_YANDX_0_0/VGA_Square_Logic_YANDX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_YANDX_0_0 || ORIG_REF_NAME==VGA_Square_Logic_YANDX_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_OR_2B_0_0/VGA_Square_Logic_DS_OR_2B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_OR_2B_0_0 || ORIG_REF_NAME==VGA_Square_Logic_DS_OR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_SideReached_0/VGA_Square_Logic_SideReached_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_SideReached_0 || ORIG_REF_NAME==VGA_Square_Logic_SideReached_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_c_counter_binary_0_1/VGA_Square_Logic_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_c_counter_binary_0_1 || ORIG_REF_NAME==VGA_Square_Logic_c_counter_binary_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_Toggle_X_Up_0/VGA_Square_Logic_Toggle_X_Up_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_Toggle_X_Up_0 || ORIG_REF_NAME==VGA_Square_Logic_Toggle_X_Up_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_NOT_0_1/VGA_Square_Logic_DS_NOT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_NOT_0_1 || ORIG_REF_NAME==VGA_Square_Logic_DS_NOT_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_startWithX_Up_High_0/VGA_Square_Logic_startWithX_Up_High_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_startWithX_Up_High_0 || ORIG_REF_NAME==VGA_Square_Logic_startWithX_Up_High_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_VGA_Square_Logic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/MovingSquare_VGA_Square_Logic_0_0.xci
# IP: The module: 'MovingSquare_VGA_Square_Logic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_AND_2B_0_0/VGA_Square_Logic_DS_AND_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_AND_2B_0_0 || ORIG_REF_NAME==VGA_Square_Logic_DS_AND_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_NOT_0_0/VGA_Square_Logic_DS_NOT_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_NOT_0_0 || ORIG_REF_NAME==VGA_Square_Logic_DS_NOT_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_X_NOT_GT_endX_0/VGA_Square_Logic_X_NOT_GT_endX_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_X_NOT_GT_endX_0 || ORIG_REF_NAME==VGA_Square_Logic_X_NOT_GT_endX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InWidthSquare_0/VGA_Square_Logic_InWidthSquare_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InWidthSquare_0 || ORIG_REF_NAME==VGA_Square_Logic_InWidthSquare_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InWidthSquare_1/VGA_Square_Logic_InWidthSquare_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InWidthSquare_1 || ORIG_REF_NAME==VGA_Square_Logic_InWidthSquare_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_X_NOT_LT_startX_0/VGA_Square_Logic_X_NOT_LT_startX_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_X_NOT_LT_startX_0 || ORIG_REF_NAME==VGA_Square_Logic_X_NOT_LT_startX_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_Y_NOT_LT_startY_0/VGA_Square_Logic_Y_NOT_LT_startY_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_Y_NOT_LT_startY_0 || ORIG_REF_NAME==VGA_Square_Logic_Y_NOT_LT_startY_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InSquare_0/VGA_Square_Logic_InSquare_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InSquare_0 || ORIG_REF_NAME==VGA_Square_Logic_InSquare_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_InSquareAndCanDraw_0/VGA_Square_Logic_InSquareAndCanDraw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_InSquareAndCanDraw_0 || ORIG_REF_NAME==VGA_Square_Logic_InSquareAndCanDraw_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_YANDX_0_0/VGA_Square_Logic_YANDX_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_YANDX_0_0 || ORIG_REF_NAME==VGA_Square_Logic_YANDX_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_OR_2B_0_0/VGA_Square_Logic_DS_OR_2B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_OR_2B_0_0 || ORIG_REF_NAME==VGA_Square_Logic_DS_OR_2B_0_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_SideReached_0/VGA_Square_Logic_SideReached_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_SideReached_0 || ORIG_REF_NAME==VGA_Square_Logic_SideReached_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_c_counter_binary_0_1/VGA_Square_Logic_c_counter_binary_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_c_counter_binary_0_1 || ORIG_REF_NAME==VGA_Square_Logic_c_counter_binary_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_Toggle_X_Up_0/VGA_Square_Logic_Toggle_X_Up_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_Toggle_X_Up_0 || ORIG_REF_NAME==VGA_Square_Logic_Toggle_X_Up_0} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_DS_NOT_0_1/VGA_Square_Logic_DS_NOT_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_DS_NOT_0_1 || ORIG_REF_NAME==VGA_Square_Logic_DS_NOT_0_1} -quiet] -quiet

# IP: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_startWithX_Up_High_0/VGA_Square_Logic_startWithX_Up_High_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_Square_Logic_startWithX_Up_High_0 || ORIG_REF_NAME==VGA_Square_Logic_startWithX_Up_High_0} -quiet] -quiet

# XDC: c:/ProgramData/Xilinx/Projects/MovingSquareComplete/MovingSquareComplete.srcs/sources_1/bd/MovingSquare/ip/MovingSquare_VGA_Square_Logic_0_0/src/VGA_Square_Logic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MovingSquare_VGA_Square_Logic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
